check-info:
  tags:
    - build
  stage: init
  timeout: 5m
  extends: .default_env_dump
  script:
    # BUILDTYPE 체크 reference commit의 branch name에서 두 번째 자리의 항목으로 타입 체크
    # all/server/client 로 반응함
    # branch name이 feature/server/16-server-ci-dc 와 같은 경우 BUILDTYPE=server
    - $SPLITS = $CI_COMMIT_REF_NAME -split "/"
    - $BUILDTYPE = $SPLITS[1]
    - echo "BUILDTYPE=$BUILDTYPE" > check.env

    # Git TAG를 통한 Version 확인
    # Git TAG는 "2024.12.9.1-29-g73b3095" 처럼 <TAG>-<TAG 이후 COMMIT 수>-<현재 COMMIT ID> 형태로 이루어져 있음
    # TAG와 함께 PUSH 한 0 번째 COMMIT 만 DEPLOY 하도록 TAGGEDVERSION 작성
    - $VERSION=(& git describe --abbrev=7 --long --tags || $null)
    - if ( -not $VERSION ) { Write-Host $CYAN"Version tag not found."$ESC; echo "TAGGEDVERSION=$null" >> check.env; Exit 0 }
    - $VERSION_SPLIT = $VERSION -split "-"
    - if ($VERSION_SPLIT[1] -ne "0") { Write-Host $CYAN"New tag not detected."$ESC; echo "TAGGEDVERSION=$null" >> check.env; Exit 0 }

    - $TAGGEDVERSION = $VERSION_SPLIT[0]
    - Write-Host $CYAN"Ver = $TAGGEDVERSION"$ESC
    - echo "TAGGEDVERSION=$TAGGEDVERSION" >> check.env
  artifacts:
    reports:
      dotenv: check.env
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
      when: on_success
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: on_success
    - when: never
