version: "3.8"

services:
  jdgworkerservice:
    image: jdgworkerservice
    restart: always
    networks:
      - local-dev
    ports:
      - "7066:7066" # 외부포트:내부포트

  redis: # container name
    image: redis:latest
    ports: # 바인딩할 포트:내부 포트
      - ${REDIS_BINDING_PORT}:${REDIS_PORT}
    restart: always
    networks:
      - local-dev

networks:
  local-dev:
    external: true