version: "3"
services:
  postgres:
    image: postgres:latest
    restart: always
    # command: -c ssl=on -c ssl_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem -c ssl_key_file=/etc/ssl/private/ssl-cert-snakeoil.key
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: jdg
      POSTGRES_PASSWORD: 7596
      PGDATA: /var/lib/postgresql/data
    volumes:
      #- ./data:/var/lib/postgresql/data
      - D:/Docker/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin4:
    image: elestio/pgadmin:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: jang75967@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 7596
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - "8080:8080"
    volumes:
      - ./servers.json:/pgadmin4/servers.json
